### ISSUE TITLE
Thread vs Fiber contention

### ISSUE THREAD

**Issue by ioquatix** [noahgibbs/fiber_basic_benchmarks#2]
The thread example doesn't create one thread per worker on the master side, instead opting for `IO.select`.

In order to really test the same thing, probably you should make one thread per worker on the master side, the same way you create one fiber per worker on the master side.

**Comment by noahgibbs** [comment]
I've added an N-thread version of this test in commit 89c043e. I'll be speed-testing it soon.

**Comment by noahgibbs** [comment]
At least on my local Mac, the one-thread-per-worker version seems faster. I'm getting larger-scale more-trial EC2 numbers now.

**Comment by noahgibbs** [comment]
Looks like with older Rubies (2.5 and before) the one-thread-per-worker-in-master (a.k.a. thread_test_multi_master.rb) is *much* slower, around 175%-200% the time, while in Ruby 2.6.5 it's close, but still slower -- roughly 28 seconds for multi_master versus 25 for the version with IO.select. So that's around 10% slower, give or take.

I can't tell if that's a fairer representation of thread performance or not, but including both seems reasonable in any case. Thanks for the suggestion!

**Comment by ioquatix** [comment]
Yeah, I know it's hard to be objective.

From reading the source code, it looks like Ruby has it's own thread pool, or at least it caches a certain number of threads. I'd need to check again as I don't know if it's enabled by default or how it works.

In any case, in the real world, some overhead is avoided by using thread pool.

But this can't always work.

A worker pool that makes one thread per job is probably the worst case. Using some kind of pool, maybe a middle ground and more typical when systems are built with performance in mind.
